### ISSUE TITLE
Stored procedure with user-defined data types as parameters

### ISSUE THREAD

**Issue by NickDarvey** [demetrixbio/FSharp.Data.Npgsql#105]
This might not be supported, in which case I'll close this. I thought it was worth opening anyway as it might help the next person who goes to try it.

## Repro

```sql
CREATE TYPE example.my_proc_parameter AS (
  id text
);

CREATE PROCEDURE example.my_proc (
  xs example.my_proc_parameter[]
)
LANGUAGE PLPGSQL
AS
$$
BEGIN

DELETE FROM example.things
WHERE id IN (SELECT id FROM unnest(xs));

END;
$$
;
```

```fsharp
use sql = conn |> db.CreateCommand<"
  CALL example.my_proc(@x)
">

```

## Expected

I'm able to call `sql.AsyncExecute()` with an `my_proc_parameter array`.

## Actual

```
The type provider 'FSharp.Data.Npgsql.NpgsqlProviders' reported an error: Couldn't find PostgreSQL type with OID 16559
```

However, if we lose the user-defined type and pass built-in types like text, it works. (See details.)

<details>

```sql

CREATE PROCEDURE example.my_proc (
  xs text[]
)
LANGUAGE PLPGSQL
AS
$$
BEGIN

DELETE FROM example.things
WHERE id IN (SELECT * FROM unnest(xs));

END;
$$
;
```

</details>

**Comment by kerams** [comment]
Custom composite types are not supported because in Npgsql 5 they removed dynamic mapping of types (via `ExpandoObject`). Nowadays you need to define a class in the assembly for the composite yourself (i.e. this would have to become both an erasing and generative TP). I have no idea how to do that, but if anyone could show me (in a PR here) how to emit a real class and then return an instance of it in an erased method, I'd try do resurrect https://github.com/demetrixbio/FSharp.Data.Npgsql/pull/73.

**Comment by NickDarvey** [comment]
>this would have to become both an erasing and generative TP

This is beyond my skills, but thank you for describing why.
