### ISSUE TITLE
Error converting columns in join

### ISSUE THREAD

**Issue by sandeepc24** [demetrixbio/FSharp.Data.Npgsql#20]
I have a sql where the field in select clause is null and I get following error

```
An exception of type 'System.InvalidCastException' occurred in Server.dll but was not handled in user code: 'Unable to cast object of type 'System.DBNull' to type 'System.Guid'.'
```

The sql has a join clause.
I think the columns on left joined tables should be wrapped as `option`.

**Comment by sandeepc24** [comment]
It looks like all columns except Primary key are wrapped as `option`.

**Comment by sandeepc24** [comment]
What is the best way to debug type provider?

I have checked out the Npgsql source code from here and in the solution created a new console app but when I reference the Runtime project in the console app the compiler can't find the referenced project and the console app fails to build.

**Comment by dmitry-a-morozov** [comment]
Unfortunately this is postgres+ Npgsql limitation. There is nothing the type provider can do about it.

**Comment by sandeepc24** [comment]
The issue I have is the query executes correctly but when I try to access the column value I get the above error. It looks like DataReader return it as `System.DBNull` but in the mapping in type provider it is not mapping it to None.

**Comment by sandeepc24** [comment]
This breaks at runtime.

**Comment by dmitry-a-morozov** [comment]
The type provider uses 
https://github.com/demetrixbio/FSharp.Data.Npgsql/blob/fba9eafb14dc0e933f3da6f8fc6a9f12c4dc929e/src/DesignTime/InformationSchema.fs#L230
to get information about output columns including null-ability. 
PostgreSQL engine doesn't know null-ability of derived columns. 
See https://github.com/npgsql/npgsql/issues/1693 for details. 
In case of `left join` PostgreSQL doesn't know that right part (`person_address` table in your case) becomes optional and reports columns coming from `pa.*` as non-null-able.
Run-time conversion from `DbNull` to non null-able type value fails.

**Comment by piaste** [comment]
Since PostgreSQL lacks the correct API to automatically report this nullability, and it causes a catastrophic runtime exception, then wouldn't it make sense to let the user manually force the option wrapping?

Eg. adding a `AssumeNullable` optional parameter to `NpgSqlCommand` / `NpgsqlConnection.Create`, which if set to `true` will make the type provider assign option types to all columns regardless of what `GetColumnSchema` returns.

Users will need to remember to set that flag whenever they using `left join`, and there will be some superfluous unwrapping for the main table, but at least it's a workaround.

The alternative workaround, I think would be to save the query in a view, for which PostgreSQL's always returns `attnotnull = false`, but that might not always be possible (say, if you don't control the database) and it could be a little burdensome to do every time you use a non-inner join.

**Comment by dmitry-a-morozov** [comment]
Thanks for detailed analysis. Great job.
Let's hold off on adding `AssumeNullable` flag because to me it will turn F# codebase into Java/C#-pre v8 codebase where is anything can be null. At this point I would question value of the type provider.

**Comment by Swoorup** [comment]
Currently getting stung by this. The only user-side workaround appears to be modifying the query itself?

**Comment by Swoorup** [comment]
If there are no plans from the upstream, think we should somehow provide a workaround, as it crashes some of the queries during the runtime. I can't think of anything else other than all Optional flag unfortunately. :/

**Comment by DurdSoft** [comment]
I think you could use `COALESCE`:

```sql
SELECT 
    p.firstname, 
    COALESCE(pa.id), 
    COALESCE(pa.addr1)
FROM person p
LEFT JOIN person_address pa ON p.id = pa.person_id
```

_Should_ infer to:

```fsharp
{ firstname: string
  id: Guid option
  addr1: string option }
```

No idea what affect this could have on performance for more complicated queries though.
