### ISSUE TITLE
Timescale support

### ISSUE THREAD

**Issue by sandeep-eroad** [demetrixbio/FSharp.Data.Npgsql#42]
Are there any plans to support  Timescale db - https://www.timescale.com/ ?

**Comment by daz10000** [comment]
No plans but no objections to doing it. 

Von meinem iPhone gesendet

**Comment by kerams** [comment]
It looks like Timescale utilizes partitioned tables, so #59 is a requirement here. What else would this entail? Do you know if Timescale defines custom types on its own?

**Comment by kerams** [comment]
@sandeep-eroad, if you have access to a database using Timescale, please try the lastest Nuget package and let me know if there's anything that does not work.

**Comment by Swoorup** [comment]
Trying to use with timescaledb. I am getting the following error 

```
  Program.fs(28, 27): [FS3033] The type provider 'FSharp.Data.Npgsql.NpgsqlProviders' reported an error: Unable to cast object of type 'System.DBNull' to type 'System.UInt32'.
```

```
 type SuburbDatabase = NpgsqlConnection<Connection=TPConnStr>

    [<RequireQualifiedAccess>]
    module RegionDetail =
        type SelectAll = NpgsqlCommand<"""
            SELECT * FROM evets
        """, TPConnStr, ResultType.DataReader>
```

**Comment by Swoorup** [comment]
I think I might know what the issue is. I tested this on an empty timescale database with the same error. During schema inspection some rows are returning null for `table_oid`.

This is the SQL query result of an empty timescale database from https://github.com/demetrixbio/FSharp.Data.Npgsql/blob/c1828923d145d37014f30f1b3664ec80dd989759/src/DesignTime/InformationSchema.fs#L388-L428

[timescaledb.empty.txt](https://github.com/demetrixbio/FSharp.Data.Npgsql/files/4416205/timescaledb.empty.txt)
