### ISSUE TITLE
Packages of 0.2.7-beta upwards specify exact versions of their dependencies

### ISSUE THREAD

**Issue by kerams** [demetrixbio/FSharp.Data.Npgsql#88]
![vivaldi_60ur6g2fAb](https://user-images.githubusercontent.com/5063478/79192513-26ec4a00-7e29-11ea-962b-53ebd8f02ef6.png)

vs

![vivaldi_a6ejdxpIuh](https://user-images.githubusercontent.com/5063478/79192524-2a7fd100-7e29-11ea-969e-6ca6c7ad3dfc.png)

I think this might prevent users from upgrading to a new hotfix of Npgsql for instance. Additionally, do we need the direct dependencies on FSharp.Core and System.ValueTuple?

@Swoorup

**Comment by Swoorup** [comment]
Ah this should probably be an easy fix.
The reason this came about was because I convert from nuget to paket using `paket convert-from-nuget` command, which puts the discovered dependencies into paket.dependencies. And locks the dependencies to the found version. 

https://github.com/demetrixbio/FSharp.Data.Npgsql/blob/master/paket.dependencies

Should probably be able to remove FSharp and ValueTuple and change the others to greater than match.

**Comment by Swoorup** [comment]
Fixed in https://github.com/demetrixbio/FSharp.Data.Npgsql/pull/86
